// modules/mv/labels.js
// XML internal code → { beyCode, label }
// beyCode = PDF declaration line number (e.g. "200", "221.1")
// GOLDEN RULE: PDF is the source of truth. Never place a code
// based on XML tag alone — always verify against the actual PDF.
// Last verified: 2025-04-09

export const MV_LABELS = {
  // ── Gəlirlər (sat.200–218) ────────────────────────────────────
  '1001': { beyCode:'200',       label:'Malların/işlərin/xidmətlərin təqdim edilməsindən gəlir (Cəmi)' },
  '1002': { beyCode:'200.1',     label:'Malların təqdim edilməsindən gəlir' },
  '1012': { beyCode:'203',       label:'Əmlakın icarəyə verilməsindən gəlir' },
  '1013': { beyCode:'204',       label:'Digər müəssisələrin fəaliyyətindən payçı kimi iştirakdan əldə edilmiş gəlir (dividend)' },
  '1016': { beyCode:'211',       label:'Dividendlər' },
  '1021': { beyCode:'206',       label:'Əvəzsiz əsasla təqdim edilmiş aktivlərin dəyəri' },
  '1034': { beyCode:'212',       label:'Faizlər (gəlir)' },
  '1006': { beyCode:'212.2',     label:'Digər faiz gəlirləri' },
  '1041': { beyCode:'218',       label:'ÜMUMİ GƏLİRLƏR' },
  '1042': { beyCode:'219',       label:'Ümumi gəlirdən çıxılamalar' },
  '1045': { beyCode:'219.3',     label:'Xarici valyutaların manata nisbətən məzənnəsinin dəyişməsindən yaranan mənfi fərq' },
  '1056': { beyCode:'220',       label:'Çıxılamalardan sonra ÜMUMİ GƏLİR' },
  // ── Xərclər (vergiHesab) ──────────────────────────────────────
  '1022': { beyCode:'228',       label:'Təmir xərcləri' },
  '1023': { beyCode:'228.1',     label:'Binalar, tikililər və qurğular üzrə hesablanmış təmir xərcləri' },
  '1102': { beyCode:'230',       label:'Sığorta üzrə xərclər' },
  '1106': { beyCode:'231',       label:'Digər qiymətli kağızların, borc öhdəliklərinin alınması ilə bağlı xərclər' },
  '1031': { beyCode:'222',       label:'Borcа görə faizlər və onunla bağlı olan xərclər' },
  '1076': { beyCode:'227.10',    label:'Yüksək texnologiyalar məhsulu olan hesablama texnikası üzrə hesablanmış amortizasiya' },
  // ── Verginin hesablanması (sat.237–245) ───────────────────────
  '3001': { beyCode:'237',       label:'Vergitutma məqsədləri üçün mənfəət (sat.220 - sat.236)' },
  '3002': { beyCode:'238',       label:'Mənfəət üzrə azadolmalar və güzəştlər' },
  '3003': { beyCode:'239',       label:'Zərər (sat.236 - sat.220)' },
  '3004': { beyCode:'240',       label:'Mənfəət hesabına kompensasiya edilən keçmiş illərin zərəri' },
  // ── bagliHarc: Xərclər detalları (sat.221–236) ───────────────
  '2001': { beyCode:'221',       label:'Malların təqdim edilməsi, iş görülməsi və xidmət göstərilməsi üzrə xərclər' },
  '2002': { beyCode:'221.1',     label:'Əmək haqqı və ona bərabər tutulan ödəmələr' },
  '2003': { beyCode:'221.1.1',   label:'Əcnəbi işçilər üzrə' },
  '2004': { beyCode:'221.1.2',   label:'Yerli işçilər üzrə' },
  '2005': { beyCode:'221.2',     label:'Sosial sığorta haqqları' },
  '2007': { beyCode:'221.4',     label:'Malın dəyəri' },
  '2008': { beyCode:'221.5',     label:'İcarə haqqı' },
  '1200': { beyCode:'221.5.1',   label:'Rezident şəxslər üzrə icarə haqqı' },
  '2009': { beyCode:'221.5.1.1', label:'Hüquqi şəxslər üzrə icarə haqqı' },
  '2011': { beyCode:'221.6',     label:'Ezamiyyə xərcləri' },
  '2012': { beyCode:'221.7',     label:'Enerji xərcləri' },
  '2014': { beyCode:'221.9',     label:'Yanacaq xərcləri' },
  '2016': { beyCode:'221.11',    label:'Rabitə xərcləri' },
  '2018': { beyCode:'221.13',    label:'Bank xidməti xərcləri' },
  '2019': { beyCode:'221.14',    label:'Reklam xərcləri' },
  '2020': { beyCode:'221.15',    label:'Bilavasitə malların təqdim edilməsi ilə bağlı sair xərclər' },
  '2021': { beyCode:'222',       label:'Borcа görə faizlər və onunla bağlı olan xərclər' },
  '2022': { beyCode:'222.1',     label:'Rezident üzrə faizlər' },
  '2023': { beyCode:'222.2',     label:'Faizlərlə əlaqədar xərclər və ayırmalar' },
  '2027': { beyCode:'225',       label:'Ümidsiz borclar (3 №-li Əlavə)' },
  '2031': { beyCode:'226',       label:'Elmi tədqiqat, layihə axtarışı və təcrübə konstruktor işlərinə çəkilən xərclər' },
  '2033': { beyCode:'227',       label:'Amortizasiya ayırmaları, əsas vəsaitlərin təqdim edilməsi və ləğvi üzrə gəlirdən çıxılan xərclər' },
  '2034': { beyCode:'227.1',     label:'Torpaqlar, binalar, tikililər və qurğular üzrə amortizasiya' },
  '2039': { beyCode:'227.6',     label:'Qeyri-maddi aktivlər üzrə hesablanmış amortizasiya' },
  '2140': { beyCode:'227.6.1',   label:'İstifadə müddəti məlum olmayan qeyri-maddi aktivlər üzrə amortizasiya' },
  '2040': { beyCode:'227.8',     label:'VM 114.6 — əsas vəsaitlərin qalıq dəyəri' },
  '2043': { beyCode:'231',       label:'Digər qiymətli kağızların, borc öhdəliklərinin alınması ilə bağlı xərclər' },
  '2049': { beyCode:'229',       label:'Nəqliyyat xərcləri' },
  '2050': { beyCode:'229.1',     label:'Rezident üzrə nəqliyyat xərcləri' },
  '2052': { beyCode:'230',       label:'Sığorta üzrə xərclər' },
  '2053': { beyCode:'230.1',     label:'Sığorta fəaliyyəti üzrə xərclər' },
  '2057': { beyCode:'230.2',     label:'Ödənilmiş sığorta haqqları' },
  '2062': { beyCode:'231',       label:'Digər qiymətli kağızlar, borc öhdəlikləri alınması ilə bağlı xərclər' },
  '2063': { beyCode:'232',       label:'Digər xərclər' },
  '2064': { beyCode:'233',       label:'Gəlirdən çıxılan vergilər və yığımlar' },
  '2066': { beyCode:'233.2',     label:'Əmlak vergisi' },
  '2071': { beyCode:'234',       label:'CƏMİ XƏRCLƏR' },
  '2073': { beyCode:'236',       label:'Ümumi gəlirlərdən çıxılan xərclər (sat.234 - sat.235)' },
  // ── Aktivlər (Əlavə 1) — verified vs PDF ──────────────────────
  '4001': { beyCode:'1',         label:'Cəmi aktivlər' },
  '4002': { beyCode:'1.1',       label:'Əsas vəsaitlərin dəyəri' },
  '4003': { beyCode:'1.1.1',     label:'Torpaqların yaxşılaşdırılması üzrə kapitallaşdırılmış xərclər, binalar, tikililər və qurğular' },
  '4007': { beyCode:'1.1.5',     label:'Digər əsas vəsaitlər' },
  '4045': { beyCode:'1.1.6',     label:'Yüksək texnologiyalar məhsulu olan hesablama texnikası' },
  '4008': { beyCode:'1.2',       label:'Qeyri-maddi aktivlərin dəyəri' },
  '4050': { beyCode:'1.2.1',     label:'İstifadə müddəti məlum olmayan qeyri-maddi aktivlərin dəyəri' },
  '4040': { beyCode:'1.3',       label:'Ehtiyatlar' },
  '4041': { beyCode:'1.3.1',     label:'Hazır məhsul' },
  '4005': { beyCode:'1.3.2',     label:'Mallar' },
  '4042': { beyCode:'1.3.3',     label:'Bitməmiş istehsalat' },
  '4043': { beyCode:'1.3.4',     label:'Sair ehtiyatlar' },
  '4014': { beyCode:'1.4',       label:'Debitor borcları' },
  '4015': { beyCode:'1.4.1',     label:'Dövlət büdcəsinə (vergilər üzrə) debitor borcu' },
  '4016': { beyCode:'1.4.2',     label:'Sair debitor borcları' },
  '4017': { beyCode:'1.5',       label:'Pul vəsaitləri' },
  '4022': { beyCode:'1.10',      label:'Digər aktivlər' },
  '4004': { beyCode:'—', label:'Səhmlər və iştirak payları üzrə maliyyə qoyuluşları' },
  '4006': { beyCode:'—', label:'Göstərici 4006' }, '4009': { beyCode:'—', label:'Göstərici 4009' },
  '4010': { beyCode:'—', label:'Göstərici 4010' }, '4011': { beyCode:'—', label:'Göstərici 4011' },
  '4012': { beyCode:'—', label:'Göstərici 4012' }, '4013': { beyCode:'—', label:'Göstərici 4013' },
  '4018': { beyCode:'—', label:'Göstərici 4018' }, '4019': { beyCode:'—', label:'Göstərici 4019' },
  '4020': { beyCode:'—', label:'Göstərici 4020' }, '4021': { beyCode:'—', label:'Göstərici 4021' },
  '4044': { beyCode:'—', label:'Göstərici 4044' }, '4046': { beyCode:'—', label:'Göstərici 4046' },
  '4047': { beyCode:'—', label:'Göstərici 4047' }, '4048': { beyCode:'—', label:'Göstərici 4048' },
  '4049': { beyCode:'—', label:'Göstərici 4049' }, '4051': { beyCode:'—', label:'Göstərici 4051' },
  '4053': { beyCode:'—', label:'Göstərici 4053' }, '4054': { beyCode:'—', label:'Göstərici 4054' },
  // ── Kapital & Öhdəliklər (Əlavə 1) — verified vs PDF ──────────
  '4023': { beyCode:'2',         label:'Cəmi kapital və öhdəliklər' },
  '5001': { beyCode:'2.1',       label:'Cəmi kapital' },
  '4024': { beyCode:'2.1.1',     label:'Nizamnamə kapitalı' },
  '4025': { beyCode:'2.1.2',     label:'Hesabat dövrünün xalis mənfəəti' },
  '4026': { beyCode:'2.1.3',     label:'Əvvəlki illər üzrə bölüşdürülməmiş mənfəət' },
  '7001': { beyCode:'2.1.4',     label:'Emissiya gəliri' },
  '7002': { beyCode:'2.1.5',     label:'Kapital ehtiyatları' },
  '6001': { beyCode:'2.2',       label:'Cəmi öhdəliklər' },
  '4027': { beyCode:'2.2.1',     label:'Kreditor borcları' },
  '4028': { beyCode:'2.2.1.1',   label:'Bank kreditləri' },
  '4029': { beyCode:'2.2.1.1.1', label:'O cümlədən xarici borclar' },
  '4031': { beyCode:'2.2.1.2',   label:'Alınmış avanslar' },
  '4052': { beyCode:'2.2.1.5',   label:'Sair kreditor borcları' },
  '4032': { beyCode:'2.2.1.5.1', label:'O cümlədən xarici borclar (sair)' },
  '4034': { beyCode:'2.2.3',     label:'Digər öhdəliklər' },
  '4033': { beyCode:'—', label:'Göstərici 4033' },
  '4030': { beyCode:'—', label:'Göstərici 4030' },
  '5050': { beyCode:'—', label:'Xüsusi vergi rejimi' },
};

export function mvInfo(kod) {
  return MV_LABELS[kod] || { beyCode: '—', label: `Göstərici ${kod}` };
}
