// modules/mv/labels.js
// Complete PDF declaration structure + XML code mapping.
// GOLDEN RULE: PDF is the single source of truth for line order and labels.
// Last verified against official template: 2026-04-13

// ── XML code → beyCode + label (backward compat) ─────────────────
export const MV_LABELS = {
  '1001':{beyCode:'200',label:'Malların təqdim edilməsindən (işlərin görülməsindən, xidmətlərin göstərilməsindən) gəlir'},
  '1002':{beyCode:'200.1',label:'Malların təqdim edilməsindən gəlir'},
  '1012':{beyCode:'203',label:'Əmlakın icarəyə verilməsindən gəlir'},
  '1013':{beyCode:'204',label:'Digər müəssisələrin fəaliyyətindən payçı kimi iştirakdan əldə edilmiş gəlir'},
  '1016':{beyCode:'211',label:'Dividendlər'},'1021':{beyCode:'206',label:'Əvəzsiz əsasla təqdim edilmiş aktivlərin dəyəri'},
  '1034':{beyCode:'212',label:'Faizlər'},'1006':{beyCode:'212.2',label:'Digər faiz gəlirləri'},
  '1041':{beyCode:'218',label:'ÜMUMİ GƏLİRLƏR'},'1042':{beyCode:'219',label:'Ümumi gəlirdən çıxılmalar'},
  '1045':{beyCode:'219.3',label:'Xarici valyutaların manata nisbətən məzənnəsinin dəyişməsindən yaranan mənfi fərq'},
  '1056':{beyCode:'220',label:'Çıxılmalardan sonra ÜMUMİ GƏLİR'},
  '1076':{beyCode:'227.10',label:'Yüksək texnologiyalar məhsulu olan hesablama texnikası üzrə hesablanmış amortizasiya'},
  '1022':{beyCode:'228',label:'Təmir xərcləri'},'1023':{beyCode:'228.1',label:'Binalar, tikililər və qurğular üzrə təmir'},
  '1102':{beyCode:'230',label:'Sığorta üzrə xərclər'},'1106':{beyCode:'231',label:'İstiqrazlar, digər qiymətli kağızlar ilə bağlı xərclər'},
  '1031':{beyCode:'222',label:'Borca görə faizlər'},'1200':{beyCode:'221.5.1',label:'Rezident şəxslər üzrə icarə haqqı'},
  '2001':{beyCode:'221',label:'Malların təqdim edilməsi üzrə xərclər'},'2002':{beyCode:'221.1',label:'Əmək haqqı'},
  '2003':{beyCode:'221.1.1',label:'Əcnəbi işçilər üzrə'},'2004':{beyCode:'221.1.2',label:'Yerli işçilər üzrə'},
  '2005':{beyCode:'221.2',label:'Sosial sığorta haqları'},'2007':{beyCode:'221.4',label:'Malın dəyəri'},
  '2008':{beyCode:'221.5',label:'İcarə haqqı'},'2009':{beyCode:'221.5.1.1',label:'Hüquqi şəxslər üzrə'},
  '2011':{beyCode:'221.6',label:'Ezamiyyə xərcləri'},'2012':{beyCode:'221.7',label:'Enerji xərcləri'},
  '2014':{beyCode:'221.9',label:'Yanacaq xərcləri'},'2016':{beyCode:'221.11',label:'Rabitə xərcləri'},
  '2018':{beyCode:'221.13',label:'Bank xidməti xərcləri'},'2019':{beyCode:'221.14',label:'Reklam xərcləri'},
  '2020':{beyCode:'221.15',label:'Bilavasitə sair xərclər'},
  '2021':{beyCode:'222',label:'Borca görə faizlər'},'2022':{beyCode:'222.1',label:'Rezident üzrə faizlər'},
  '2023':{beyCode:'222.2',label:'Faizlərlə əlaqədar xərclər'},
  '2027':{beyCode:'225',label:'Ümidsiz borclar'},'2031':{beyCode:'226',label:'Elmi tədqiqat xərcləri'},
  '2033':{beyCode:'227',label:'Amortizasiya ayırmaları'},'2034':{beyCode:'227.1',label:'Torpaqlar, binalar üzrə amortizasiya'},
  '2039':{beyCode:'227.6',label:'Qeyri-maddi aktivlər üzrə amortizasiya'},
  '2140':{beyCode:'227.6.1',label:'İstifadə müddəti məlum olmayan qeyri-maddi aktivlər üzrə amortizasiya'},
  '2040':{beyCode:'227.8',label:'VM 114.6 — əsas vəsaitlərin qalıq dəyəri'},
  '2043':{beyCode:'231',label:'İstiqrazlar, qiymətli kağızlar xərcləri'},
  '2049':{beyCode:'229',label:'Nəqliyyat xərcləri'},'2050':{beyCode:'229.1',label:'Rezident üzrə nəqliyyat'},
  '2052':{beyCode:'230',label:'Sığorta üzrə xərclər'},'2053':{beyCode:'230.1',label:'Sığorta fəaliyyəti xərcləri'},
  '2057':{beyCode:'230.2',label:'Ödənilmiş sığorta haqları'},
  '2062':{beyCode:'231',label:'Qiymətli kağızlar ilə bağlı xərclər'},
  '2063':{beyCode:'232',label:'Digər xərclər'},'2064':{beyCode:'233',label:'Gəlirdən çıxılan vergilər və yığımlar'},
  '2066':{beyCode:'233.2',label:'Əmlak vergisi'},'2071':{beyCode:'234',label:'CƏMİ XƏRCLƏR'},
  '2073':{beyCode:'236',label:'Ümumi gəlirlərdən çıxılan xərclər (sət.234 - sət.235)'},
  '3001':{beyCode:'237',label:'Vergitutma məqsədləri üçün mənfəət'},'3002':{beyCode:'238',label:'Mənfəət üzrə azadolmalar və güzəştlər'},
  '3003':{beyCode:'239',label:'Zərər'},'3004':{beyCode:'241',label:'Vergiyə cəlb olunan mənfəət'},
  '3005':{beyCode:'242',label:'Mənfəət vergisinin dərəcəsi'},'3006':{beyCode:'243',label:'Mənfəət vergisi'},
  '3107':{beyCode:'244',label:'Azaldılmalı verginin məbləği'},'3010':{beyCode:'245',label:'Ödənilməli mənfəət vergisi'},
  '3014':{beyCode:'249',label:'VM-nə əsasən gəlirdən çıxılmayan xərclər'},'3017':{beyCode:'249.3',label:'Gəlirdən çıxılmayan digər xərclər'},
  // Aktivlər
  '4001':{beyCode:'1',label:'Cəmi aktivlər'},'4002':{beyCode:'1.1',label:'Əsas vəsaitlərin dəyəri'},
  '4003':{beyCode:'1.1.1',label:'Torpaqlar, binalar, tikililər və qurğular'},
  '4007':{beyCode:'1.1.5',label:'Digər əsas vəsaitlər'},'4045':{beyCode:'1.1.6',label:'Yüksək texnologiyalar məhsulu hesablama texnikası'},
  '4008':{beyCode:'1.2',label:'Qeyri-maddi aktivlər'},'4050':{beyCode:'1.2.1',label:'İstifadə müddəti məlum olmayan qeyri-maddi aktivlər'},
  '4040':{beyCode:'1.3',label:'Ehtiyatlar'},'4041':{beyCode:'1.3.1',label:'Hazır məhsul'},
  '4042':{beyCode:'1.3.2',label:'Bitməmiş istehsalat'},'4043':{beyCode:'1.3.3',label:'Bitməmiş tikinti'},
  '4005':{beyCode:'1.3.4',label:'Mallar'},'4014':{beyCode:'1.4',label:'Debitor borcları'},
  '4015':{beyCode:'1.4.1',label:'Dövlət büdcəsinə debitor borcu'},'4016':{beyCode:'1.4.2',label:'Sair debitor borcları'},
  '4017':{beyCode:'1.5',label:'Pul vəsaitləri'},'4022':{beyCode:'1.10',label:'Digər aktivlər'},
  // Kapital & Öhdəliklər
  '4023':{beyCode:'2',label:'Cəmi kapital və öhdəliklər'},'5001':{beyCode:'2.1',label:'Cəmi kapital'},
  '4024':{beyCode:'2.1.1',label:'Nizamnamə kapitalı'},'4025':{beyCode:'2.1.2',label:'Hesabat dövrünün xalis mənfəəti'},
  '4026':{beyCode:'2.1.3',label:'Əvvəlki illər üzrə bölüşdürülməmiş mənfəət'},
  '7001':{beyCode:'2.1.4',label:'Emissiya gəliri'},'7002':{beyCode:'2.1.5',label:'Kapital ehtiyatları'},
  '6001':{beyCode:'2.2',label:'Cəmi öhdəliklər'},'4027':{beyCode:'2.2.1',label:'Kreditor borcları'},
  '4028':{beyCode:'2.2.1.1',label:'Bank kreditləri'},'4029':{beyCode:'2.2.1.1.1',label:'O cümlədən xarici borclar'},
  '4031':{beyCode:'2.2.1.2',label:'Alınmış avanslar'},'4052':{beyCode:'2.2.1.5',label:'Sair kreditor borcları'},
  '4032':{beyCode:'2.2.1.5.1',label:'O cümlədən xarici borclar (sair)'},'4034':{beyCode:'2.2.3',label:'Digər öhdəliklər'},
  '5050':{beyCode:'—',label:'Xüsusi vergi rejimi'},
};

export function mvInfo(kod) { return MV_LABELS[kod]||{beyCode:'—',label:`Göstərici ${kod}`}; }

// ── PDF STRUCTURE ─────────────────────────────────────────────────
// type: H=section header, L=data line, T=total/bold line
// xml: XML göstərici code (null = no data in XML for this line)
// lvl: indentation depth
export const PDF_STRUCTURE = [
  {type:'H',label:'Hesabat Dövrünün GƏLİRLƏRİ (ƏDV-siz və aksizsiz)'},
  {type:'L',bey:'200',label:'Malların təqdim edilməsindən (işlərin görülməsindən, xidmətlərin göstərilməsindən) gəlir',xml:'1001',lvl:0},
  {type:'L',bey:'200.1',label:'Malların təqdim edilməsindən gəlir',xml:'1002',lvl:1},
  {type:'L',bey:'200.1.1',label:'Pərakəndə satışdan gəlir',xml:null,lvl:2},
  {type:'L',bey:'200.1.1.1',label:'O cümlədən elektron ticarətdən',xml:null,lvl:3},
  {type:'L',bey:'200.1.2',label:'Topdan satışdan gəlir',xml:null,lvl:2},
  {type:'L',bey:'200.1.2.1',label:'o cümlədən elektron ticarətdən',xml:null,lvl:3},
  {type:'L',bey:'200.2',label:'İşlərin görülməsindən və xidmətlərin göstərilməsindən gəlir',xml:null,lvl:1},
  {type:'L',bey:'200.2.1',label:'Sığorta fəaliyyətindən gəlirlər',xml:null,lvl:2},
  {type:'L',bey:'200.2.1.1',label:'Sığorta ehtiyatlarının qaytarılması üzrə',xml:null,lvl:3},
  {type:'L',bey:'200.2.2',label:'İctimai iaşə fəaliyyətindən gəlirlər',xml:null,lvl:2},
  {type:'L',bey:'200.2.3',label:'Elektron xidmətdən',xml:null,lvl:2},
  {type:'L',bey:'201',label:'Amortizasiya olunan əsas vəsaitlərin təqdim edilməsindən gəlir',xml:null,lvl:0},
  {type:'L',bey:'202',label:'Amortizasiya olunmayan aktivlərin təqdim edilməsindən gəlir',xml:null,lvl:0},
  {type:'L',bey:'203',label:'Əmlakın icarəyə verilməsindən gəlir',xml:'1012',lvl:0},
  {type:'L',bey:'203.1',label:'Daşınan əmlakın icarəyə verilməsindən gəlir',xml:null,lvl:1},
  {type:'L',bey:'203.2',label:'Daşınmaz əmlakın icarəyə verilməsindən gəlir',xml:null,lvl:1},
  {type:'L',bey:'204',label:'Digər müəssisələrin fəaliyyətindən payçı kimi iştirakdan əldə edilmiş gəlir (dividend istisna olmaqla)',xml:'1013',lvl:0},
  {type:'L',bey:'204.1',label:'50%-dən çox səs hüququ verən səhmi olan müəssisələrdə iştirakdan gəlir',xml:null,lvl:1},
  {type:'L',bey:'204.2',label:'50 faizədək səs hüququ verən səhmi olan müəssisələrdə iştirakdan gəlir',xml:null,lvl:1},
  {type:'L',bey:'205',label:'İştirak faizinə görə birgə fəaliyyətdən əldə edilmiş gəlir',xml:null,lvl:0},
  {type:'L',bey:'205.1',label:'Birgə fəaliyyət üzrə ümumi gəlir',xml:null,lvl:1},
  {type:'L',bey:'205.2',label:'İştirak faizi',xml:null,lvl:1},
  {type:'L',bey:'206',label:'Əvəzsiz əsasla təqdim edilmiş aktivlərin dəyəri',xml:'1021',lvl:0},
  {type:'L',bey:'207',label:'Səhmlər, istiqrazlar və digər qiymətli kağızların, iştirak paylarının, borc öhdəliklərinin satışından əldə edilmiş gəlirlər',xml:null,lvl:0},
  {type:'L',bey:'207.1',label:'Səhmlərin və iştirak paylarının satışından əldə edilmiş gəlir',xml:null,lvl:1},
  {type:'L',bey:'207.2',label:'İstiqrazların satışından əldə edilmiş gəlir',xml:null,lvl:1},
  {type:'L',bey:'207.3',label:'Digər qiymətli kağızların satışından əldə edilmiş gəlir',xml:null,lvl:1},
  {type:'L',bey:'207.4',label:'Borc öhdəliklərinin satışından əldə edilmiş gəlir',xml:null,lvl:1},
  {type:'L',bey:'207.5',label:'Borc tələblərinin satışından əldə edilmiş gəlir',xml:null,lvl:1},
  {type:'L',bey:'208',label:'İddia müddəti ötmüş və kreditorlar tərəfindən silinmiş kreditor borcları üzrə gəlir',xml:null,lvl:0},
  {type:'L',bey:'209',label:'Uduşlar',xml:null,lvl:0},
  {type:'L',bey:'210',label:'Royalti',xml:null,lvl:0},
  {type:'L',bey:'210.1',label:'Azərbaycan Respublikasının hüdudlarından kənarda əldə edilmiş royaltidən gəlir',xml:null,lvl:1},
  {type:'L',bey:'211',label:'Dividendlər',xml:'1016',lvl:0},
  {type:'L',bey:'211.1',label:'Azərbaycan Respublikasında alınmış dividendlər',xml:null,lvl:1},
  {type:'L',bey:'211.2',label:'Azərbaycan Respublikasının hüdudlarından kənarda alınmış dividendlər',xml:null,lvl:1},
  {type:'L',bey:'212',label:'Faizlər',xml:'1034',lvl:0},
  {type:'L',bey:'212.1',label:'Bank fəaliyyətindən faizlər',xml:null,lvl:1},
  {type:'L',bey:'212.2',label:'Digər faiz gəlirləri',xml:'1006',lvl:1},
  {type:'L',bey:'213',label:'Əvvəllər gəlirdən çıxılmış ehtiyatın azaldılmasından gəlir',xml:null,lvl:0},
  {type:'L',bey:'214',label:'Xarici valyutaların manata nisbətən müsbət məzənnə fərqi',xml:null,lvl:0},
  {type:'L',bey:'215',label:'Əvvəllər gəlirdən çıxılmış xərcin, zərərin və ya ümidsiz borcun ödənilməsindən gəlir',xml:null,lvl:0},
  {type:'L',bey:'216',label:'Vergilərin uçotu metodunun dəyişilməsi nəticəsində yaranan keçmiş illərin gəliri',xml:null,lvl:0},
  {type:'L',bey:'217',label:'Yuxarıdakı bəndlərdə nəzərdə tutulmayan digər gəlirlər',xml:null,lvl:0},
  {type:'L',bey:'217.1',label:'İxrac məqsədli neft-qaz fəaliyyəti üzrə alınmış gəlirlər',xml:null,lvl:1},
  {type:'L',bey:'217.2',label:'Azərbaycan Respublikasının hüdudlarından kənarda əldə edilmiş gəlirlər',xml:null,lvl:1},
  {type:'L',bey:'217.3',label:'Transfer qiymətlərin tətbiq edilməsindən əldə edilmiş gəlirlər',xml:null,lvl:1},
  {type:'L',bey:'217.4',label:'AR-ın rezidenti hesab edilən şəxsin nəzarət olunan xarici müəssisədən əldə edilən vergi tutulan gəlirləri',xml:null,lvl:1},
  {type:'L',bey:'217.5',label:'Tibb müəssisələri tərəfindən ƏDV hesablanarkən VM 174.5 maddəsinə əsasən ƏDV azaldılmasından əldə edilən gəlirlər',xml:null,lvl:1},
  {type:'T',bey:'218',label:'Ü M U M İ   G Ə L İ R L Ə R',xml:'1041',lvl:0},
  {type:'L',bey:'219',label:'Ümumi gəlirdən çıxılmalar',xml:'1042',lvl:0},
  {type:'L',bey:'219.1',label:'Rezident tərəfindən ödəmə mənbəyində vergiyə cəlb olunan dividend gəlirləri',xml:null,lvl:1},
  {type:'L',bey:'219.2',label:'Təqdim olunmuş (amortizasiya olunmayan) aktivlərin qalıq dəyəri',xml:null,lvl:1},
  {type:'L',bey:'219.3',label:'Xarici valyutaların manata nisbətən məzənnəsinin dəyişməsindən yaranan mənfi fərq',xml:'1045',lvl:1},
  {type:'L',bey:'219.4',label:'Gəlirlər üzrə azadolmalar və güzəştlər (5 №-li Əlavə ilə təqdim olunur)',xml:null,lvl:1},
  {type:'L',bey:'219.5',label:'Bina tikintisi fəaliyyəti üzrə dövlətə ayrılan sahələrin təqdim edilməsi üzrə gəlir',xml:null,lvl:1},
  {type:'L',bey:'219.6',label:'Dəqiqləşdirilən əməliyyatlar hesabına azaldılan gəlir',xml:null,lvl:1},
  {type:'L',bey:'219.7',label:'Vəkil qurumlarının tərkibində göstərilən vəkillik fəaliyyəti ilə bağlı ödənişlər',xml:null,lvl:1},
  {type:'T',bey:'220',label:'Çıxılmalardan sonra Ü M U M İ   G Ə L İ R',xml:'1056',lvl:0},
  {type:'H',label:'Hesabat dövründə gəlirlərin əldə edilməsi ilə bağlı XƏRCLƏR'},
  {type:'L',bey:'221',label:'Malların təqdim edilməsi, iş görülməsi və xidmət göstərilməsi üzrə xərclər',xml:'2001',lvl:0},
  {type:'L',bey:'221.1',label:'Əmək haqqı və ona bərabər tutulan ödəmələr',xml:'2002',lvl:1},
  {type:'L',bey:'221.1.1',label:'Əcnəbi işçilər üzrə',xml:'2003',lvl:2},
  {type:'L',bey:'221.1.2',label:'Yerli işçilər üzrə',xml:'2004',lvl:2},
  {type:'L',bey:'221.2',label:'Sosial sığorta haqları',xml:'2005',lvl:1},
  {type:'L',bey:'221.3',label:'Xammal və materiallar',xml:null,lvl:1},
  {type:'L',bey:'221.4',label:'Malın dəyəri',xml:'2007',lvl:1},
  {type:'L',bey:'221.5',label:'İcarə haqqı',xml:'2008',lvl:1},
  {type:'L',bey:'221.5.1',label:'Rezident şəxslər üzrə icarə haqqı',xml:'1200',lvl:2},
  {type:'L',bey:'221.5.1.1',label:'Hüquqi şəxslər üzrə',xml:'2009',lvl:3},
  {type:'L',bey:'221.5.1.2',label:'Fiziki şəxslər üzrə',xml:null,lvl:3},
  {type:'L',bey:'221.5.2',label:'Qeyri rezidentlər üzrə icarə haqqı',xml:null,lvl:2},
  {type:'L',bey:'221.6',label:'Ezamiyyə xərcləri',xml:'2011',lvl:1},
  {type:'L',bey:'221.7',label:'Enerji xərcləri',xml:'2012',lvl:1},
  {type:'L',bey:'221.8',label:'Qaz xərcləri',xml:null,lvl:1},
  {type:'L',bey:'221.9',label:'Yanacaq xərcləri',xml:'2014',lvl:1},
  {type:'L',bey:'221.10',label:'Su və kanalizasiya xərcləri',xml:null,lvl:1},
  {type:'L',bey:'221.11',label:'Rabitə xərcləri',xml:'2016',lvl:1},
  {type:'L',bey:'221.12',label:'Mühafizə xərcləri',xml:null,lvl:1},
  {type:'L',bey:'221.13',label:'Bank xidməti üzrə xərclər',xml:'2018',lvl:1},
  {type:'L',bey:'221.14',label:'Reklam xərcləri',xml:'2019',lvl:1},
  {type:'L',bey:'221.15',label:'Bilavasitə malların təqdim edilməsi ilə bağlı sair xərclər',xml:'2020',lvl:1},
  {type:'L',bey:'221.16',label:'Qanunvericiliklə müəyyən edilmiş təbii itki normaları daxilində zayolmadan əmələgələn itkilər',xml:null,lvl:1},
  {type:'L',bey:'221.17',label:'VM-nin 119.2-ci maddəsinə əsasən normalar daxilində çəkilən xərclər',xml:null,lvl:1},
  {type:'L',bey:'222',label:'Borca görə faizlər və onunla bağlı olan xərclər',xml:'2021',lvl:0},
  {type:'L',bey:'222.1',label:'Rezident üzrə faizlər',xml:'2022',lvl:1},
  {type:'L',bey:'222.2',label:'Faizlərlə əlaqədar xərclər və ayırmalar',xml:'2023',lvl:1},
  {type:'L',bey:'222.2.1',label:'Aktivlər üzrə mümkün zərərlərin ödənilməsi üçün xüsusi ehtiyatın yaradılmasına ayırmalar',xml:null,lvl:2},
  {type:'L',bey:'222.2.2',label:'Faizlərlə bağlı digər xərclər',xml:null,lvl:2},
  {type:'L',bey:'222.3',label:'Qeyri rezident üzrə faizlər',xml:null,lvl:1},
  {type:'L',bey:'223',label:'Royalti',xml:null,lvl:0},
  {type:'L',bey:'223.1',label:'Rezident üzrə royalti',xml:null,lvl:1},
  {type:'L',bey:'223.2',label:'Qeyri rezident üzrə royalti',xml:null,lvl:1},
  {type:'L',bey:'224',label:'Xarici hüquqi şəxsin baş ofisi tərəfindən çəkilmiş və AR ilə birbaşa bağlı xərclər',xml:null,lvl:0},
  {type:'L',bey:'225',label:'Ümidsiz borclar (3 №-li Əlavə ilə təqdim olunur)',xml:'2027',lvl:0},
  {type:'L',bey:'226',label:'Elmi tədqiqat, layihə axtarış və təcrübə konstruktor işlərinə çəkilən xərclər',xml:'2031',lvl:0},
  {type:'L',bey:'227',label:'Amortizasiya ayırmaları, əsas vəsaitlərin təqdim edilməsi və ləğvi üzrə gəlirdən çıxılan xərclər',xml:'2033',lvl:0},
  {type:'L',bey:'227.1',label:'Torpaqlar, binalar, tikililər və qurğular üzrə hesablanmış amortizasiya',xml:'2034',lvl:1},
  {type:'L',bey:'227.2',label:'Maşınlar və avadanlıq üzrə hesablanmış amortizasiya',xml:null,lvl:1},
  {type:'L',bey:'227.3',label:'Nəqliyyat vasitələri üzrə hesablanmış amortizasiya',xml:null,lvl:1},
  {type:'L',bey:'227.4',label:'İş heyvanları üzrə hesablanmış amortizasiya',xml:null,lvl:1},
  {type:'L',bey:'227.5',label:'Geoloji kəşfiyyat işlərinə çəkilən xərclər üzrə hesablanmış amortizasiya',xml:null,lvl:1},
  {type:'L',bey:'227.6',label:'Qeyri-maddi aktivlər üzrə hesablanmış amortizasiya',xml:'2039',lvl:1},
  {type:'L',bey:'227.6.1',label:'İstifadə müddəti məlum olmayan qeyri-maddi aktivlər üzrə amortizasiya',xml:'2140',lvl:2},
  {type:'L',bey:'227.6.2',label:'İstifadə müddəti məlum olan qeyri-maddi aktivlər üzrə amortizasiya',xml:null,lvl:2},
  {type:'L',bey:'227.7',label:'Digər əsas vəsaitlər üzrə hesablanmış amortizasiya',xml:null,lvl:1},
  {type:'L',bey:'227.8',label:'VM-nin 114.6-cı maddəsinə əsasən çıxılan əsas vəsaitlərin qalıq dəyərinin məbləği',xml:'2040',lvl:1},
  {type:'L',bey:'227.9',label:'Təqdim edilmiş əsas vəsaitlərin qalıq dəyəri',xml:null,lvl:1},
  {type:'L',bey:'227.10',label:'Yüksək texnologiyalar hesablama texnikası üzrə hesablanmış amortizasiya',xml:'1076',lvl:1},
  {type:'L',bey:'227.11',label:'VM-nin 115.6.1-ci maddəsinə əsasən hesablanmış amortizasiya',xml:null,lvl:1},
  {type:'L',bey:'228',label:'Təmir xərcləri',xml:'1022',lvl:0},
  {type:'L',bey:'228.1',label:'Binalar, tikililər və qurğular üzrə hesablanmış təmir xərcləri',xml:'1023',lvl:1},
  {type:'L',bey:'228.2',label:'Maşınlar və avadanlıq üzrə hesablanmış təmir xərcləri',xml:null,lvl:1},
  {type:'L',bey:'228.3',label:'Nəqliyyat vasitələri üzrə hesablanmış təmir xərcləri',xml:null,lvl:1},
  {type:'L',bey:'228.4',label:'Digər əsas vəsaitlər üzrə hesablanmış təmir xərcləri',xml:null,lvl:1},
  {type:'L',bey:'228.5',label:'İcarəyə götürülmüş əsas vəsaitlərin təmir xərcləri',xml:null,lvl:1},
  {type:'L',bey:'228.6',label:'Yüksək texnologiyalar hesablama texnikası üzrə təmir xərcləri',xml:null,lvl:1},
  {type:'L',bey:'228.7',label:'Yük avtomobillərinin təmir xərcləri',xml:null,lvl:1},
  {type:'L',bey:'229',label:'Nəqliyyat xərcləri',xml:'2049',lvl:0},
  {type:'L',bey:'229.1',label:'Rezident üzrə nəqliyyat xərcləri',xml:'2050',lvl:1},
  {type:'L',bey:'229.2',label:'Qeyri rezident üzrə nəqliyyat xərcləri',xml:null,lvl:1},
  {type:'L',bey:'230',label:'Sığorta üzrə xərclər',xml:'2052',lvl:0},
  {type:'L',bey:'230.1',label:'Sığorta fəaliyyəti üzrə xərclər',xml:'2053',lvl:1},
  {type:'L',bey:'230.1.1',label:'Sığorta ehtiyatlarına ayırmalar',xml:null,lvl:2},
  {type:'L',bey:'230.1.2',label:'Təkrarsığortaya verilmiş sığorta haqları (mükafatları)',xml:null,lvl:2},
  {type:'L',bey:'230.1.3',label:'Sığorta fəaliyyəti üzrə sair xərclər',xml:null,lvl:2},
  {type:'L',bey:'230.2',label:'Ödənilmiş sığorta haqları',xml:'2057',lvl:1},
  {type:'L',bey:'231',label:'İstiqrazların, qiymətli kağızların, borc öhdəliklərinin, iştirak payı və səhmlərin alınması ilə bağlı xərclər',xml:'2062',lvl:0},
  {type:'L',bey:'231.1',label:'İstiqrazların alınması ilə bağlı xərclər',xml:null,lvl:1},
  {type:'L',bey:'231.2',label:'Digər qiymətli kağızların alınması ilə bağlı xərclər',xml:null,lvl:1},
  {type:'L',bey:'231.3',label:'Borc öhdəliklərinin alınması ilə bağlı xərclər',xml:null,lvl:1},
  {type:'L',bey:'231.4',label:'Borc tələblərinin alınması ilə bağlı xərclər',xml:null,lvl:1},
  {type:'L',bey:'231.5',label:'İştirak payı və səhmlərin alınması ilə bağlı digər xərclər',xml:null,lvl:1},
  {type:'L',bey:'232',label:'Digər xərclər',xml:'2063',lvl:0},
  {type:'L',bey:'232.1',label:'AR-ın hüdudlarından kənarda gəlirlərin əldə edilməsi ilə bağlı xərclər',xml:null,lvl:1},
  {type:'L',bey:'232.2',label:'Qeyri rezident üzrə sair xərclər',xml:null,lvl:1},
  {type:'L',bey:'232.3',label:'Uçot metodunun dəyişilməsi nəticəsində yaranan keçmiş illərin xərci',xml:null,lvl:1},
  {type:'L',bey:'232.4',label:'İştirak faizinə görə birgə fəaliyyətdən xərc',xml:null,lvl:1},
  {type:'L',bey:'232.4.1',label:'Birgə fəaliyyət üzrə ümumi xərc',xml:null,lvl:2},
  {type:'L',bey:'232.4.2',label:'İştirak faizi',xml:null,lvl:2},
  {type:'L',bey:'232.5',label:'VM-nin 109.8-ci maddəsinə əsasən xərclər',xml:null,lvl:1},
  {type:'L',bey:'233',label:'Gəlirdən çıxılan vergilər və yığımlar',xml:'2064',lvl:0},
  {type:'L',bey:'233.1',label:'Torpaq vergisi',xml:null,lvl:1},
  {type:'L',bey:'233.2',label:'Əmlak vergisi',xml:'2066',lvl:1},
  {type:'L',bey:'233.3',label:'Mədən vergisi',xml:null,lvl:1},
  {type:'L',bey:'233.4',label:'AR-da istehsal edilən tənzimlənən məhsulların ixracı zamanı dövlət büdcəsinə hesablanan yığım',xml:null,lvl:1},
  {type:'L',bey:'233.5',label:'VM 220.12 maddəsi üzrə tutulmuş sadələşdirilmiş vergi',xml:null,lvl:1},
  {type:'T',bey:'234',label:'C Ə M İ   X Ə R C L Ə R',xml:'2071',lvl:0},
  {type:'L',bey:'235',label:'Ümumi gəlirdən çıxılmayan xərclər',xml:null,lvl:0},
  {type:'L',bey:'235.1',label:'Vergidən azad olunan fəaliyyətlə bağlı bölüşdürülməsi mümkün olmayan xərclərin çıxılmayan məbləğlərinin cəmi',xml:null,lvl:1},
  {type:'L',bey:'235.1.1',label:'Vergiyə cəlb edilməyən fəaliyyətlə bağlı bölüşdürülməsi mümkün olmayan xərclərin çıxılmayan məbləği',xml:null,lvl:2},
  {type:'L',bey:'235.2',label:'Transfer qiymətlərinin tətbiq edilməsi nəticəsində azaldılan xərclər',xml:null,lvl:1},
  {type:'L',bey:'235.3',label:'Dəqiqləşdirilən əməliyyatlar hesabına azaldılan xərc',xml:null,lvl:1},
  {type:'T',bey:'236',label:'Ümumi gəlirlərdən çıxılan xərclər (sət.234 - sət.235)',xml:'2073',lvl:0},
  {type:'H',label:'Hesabat dövrü üçün verginin hesablanması'},
  {type:'L',bey:'237',label:'Vergitutma məqsədləri üçün mənfəət (sət.220 - sət.236)',xml:'3001',lvl:0},
  {type:'L',bey:'238',label:'Mənfəət üzrə azadolmalar və güzəştlər (5 №-li Əlavə ilə təqdim olunur)',xml:'3002',lvl:0},
  {type:'L',bey:'239',label:'Zərər (sət.236 - sət.220)',xml:'3003',lvl:0},
  {type:'L',bey:'240',label:'Mənfəət hesabına kompensasiya edilən keçmiş illərin zərəri',xml:null,lvl:0},
  {type:'L',bey:'241',label:'Vergiyə cəlb olunan mənfəət (sət.237-(sət.238 + sət.240))',xml:'3004',lvl:0},
  {type:'L',bey:'242',label:'Mənfəət vergisinin dərəcəsi',xml:'3005',lvl:0},
  {type:'T',bey:'243',label:'Mənfəət vergisi (sət.241 x sət.242 : 100)',xml:'3006',lvl:0},
  {type:'L',bey:'244',label:'Azaldılmalı verginin məbləği',xml:'3107',lvl:0},
  {type:'L',bey:'244.1',label:'VM-nin 106.2-ci maddəsinə əsasən azaldılmalı verginin məbləği',xml:null,lvl:1},
  {type:'L',bey:'244.2',label:'Xarici ölkələrdə ödənilmiş və nəzərə alınan mənfəət vergisinin məbləği',xml:null,lvl:1},
  {type:'L',bey:'244.3',label:'VM-nin 227.1-ci maddəsinə əsasən azaldılmalı verginin məbləği',xml:null,lvl:1},
  {type:'L',bey:'244.4',label:'VM 106.1.20 — əvvəlki 3 təqvim ilinin yekunlarına görə 75% həcmində azaldılmalı verginin məbləği',xml:null,lvl:1},
  {type:'T',bey:'245',label:'Ödənilməli mənfəət vergisinin məbləği (sət.243 - sət.244)',xml:'3010',lvl:0},
  {type:'L',bey:'246',label:'Elan edilmiş dividendlər',xml:null,lvl:0},
  {type:'L',bey:'247',label:'VM 114.4 — hesablanmış lakin növbəti illərdə nəzərə alınacaq amortizasiya məbləği',xml:null,lvl:0},
  {type:'L',bey:'248',label:'VM 115.1 — hesablanmış lakin növbəti illərdə nəzərə alınacaq təmir xərclərinin məbləği',xml:null,lvl:0},
  {type:'L',bey:'249',label:'VM-nə əsasən gəlirdən çıxılmayan xərclər',xml:'3014',lvl:0},
  {type:'L',bey:'249.1',label:'VM 109.2 maddəsinə əsasən gəlirdən çıxılmayan xərclər',xml:null,lvl:1},
  {type:'L',bey:'249.2',label:'VM 109.3 maddəsinə əsasən gəlirdən çıxılmayan xərclər',xml:null,lvl:1},
  {type:'L',bey:'249.3',label:'Gəlirdən çıxılmayan digər xərclər',xml:'3017',lvl:0},
];
